In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
x=df.iloc[:,1:5].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y=df.iloc[:,5].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [17]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)


LogisticRegression()

In [18]:
y_pred =logmodel.predict(x_test)
y_pred

array([2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2,
       0, 1, 1, 1, 2, 2, 1, 2])

In [19]:
y_test


array([2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2,
       0, 1, 2, 1, 2, 2, 1, 2])

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  9]], dtype=int64)

In [23]:
29/30

0.9666666666666667

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [28]:
y_pred =knn.predict(x_test)
y_pred

array([2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2,
       0, 1, 1, 1, 2, 2, 1, 2])

In [30]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  9]], dtype=int64)

In [31]:
29/30


0.9666666666666667

In [33]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [38]:
y_pred =nb.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  9]], dtype=int64)

In [42]:
from sklearn.svm import SVC
svm_sigmoid = SVC(kernel='sigmoid')
svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [43]:
y_pred =svm_sigmoid.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [12,  0,  0],
       [10,  0,  0]], dtype=int64)

In [44]:
8/30

0.26666666666666666

In [45]:
from sklearn.svm import SVC
svm_linear = SVC(kernel='linear')
svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [46]:
y_pred =svm_linear.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]], dtype=int64)

In [47]:
30/30


1.0

In [48]:
from sklearn.svm import SVC
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(x_train,y_train)

SVC()

In [49]:
y_pred =svm_rbf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  2,  8]], dtype=int64)

In [50]:
28/30

0.9333333333333333

In [52]:
from sklearn.svm import SVC
svm_poly = SVC(kernel='poly')
svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [57]:
y_pred =svm_poly.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]], dtype=int64)

In [55]:
30/30

1.0

In [60]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy')
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [61]:
y_pred =dt.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  3,  7]], dtype=int64)

In [62]:
27/30

0.9

In [65]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=3,criterion='entropy')
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [66]:
y_pred =rf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  2,  8]], dtype=int64)

In [67]:
28/30

0.9333333333333333